### ISSUE TITLE
Media from https://d.atry.it/i/ not loading anymore due to expired certificate

### ISSUE THREAD

**Issue by Ishidres** [DerAtrox/Bronies.de-DSB#1]
**What's the issue?**
Images such as [this](https://d.atry.it/i/_glomp2.gif) one which appear in message embeds of commands like [`!glomp`](https://github.com/DerAtrox/Bronies.de-DSB/blob/master/commands/automessage/glomp.js) aren't loading and shown anymore.

**Why is it happening?**
The links used in the message embeds load images from [https://d.atry.it](https://d.atry.it). Since the certificate used on that domain has expired on 28th Mai 2019 requests using HTTPS are being denied and can't offer any images anymore.

**How can this be solved?**
Simply renew the certificate using any available software e.g. [Certbot](https://certbot.eff.org/). Afterwards Discord should continue loading the images again after a few hours.

**Comment by DerAtrox** [comment]
Fixed
